/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Employee_ArrayList */

#ifndef _Included_Employee_ArrayList
#define _Included_Employee_ArrayList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Employee_ArrayList
 * Method:    sort_emp
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_Employee_1ArrayList_sort_1emp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
