/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Emp_Details */

#ifndef _Included_Emp_Details
#define _Included_Emp_Details
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Emp_Details
 * Method:    access_emp
 * Signature: (LEmployee;)V
 */
JNIEXPORT void JNICALL Java_Emp_1Details_access_1emp
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
