/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Call_Construct */

#ifndef _Included_Call_Construct
#define _Included_Call_Construct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Call_Construct
 * Method:    call_construct
 * Signature: (LDemo;)V
 */
JNIEXPORT void JNICALL Java_Call_1Construct_call_1construct
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
