/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sort_Array */

#ifndef _Included_Sort_Array
#define _Included_Sort_Array
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sort_Array
 * Method:    sort_array
 * Signature: (Ljava/util/ArrayList;)[I
 */
JNIEXPORT jintArray JNICALL Java_Sort_1Array_sort_1array
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
